[workspace]
members = ["puzzle-wasm", "puzzle-core", "fonts", "blueprint-core"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["jasonxue"]

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true
