[package]
name = "fonts"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[lib]
name = "fonts"
path = "src/lib.rs"

[build-dependencies]
zip = { version = "5", default-features = true }
