[package]
name = "blueprint-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "blueprint_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
