name: Build and Deploy Pages

on:
  push:
    branches: [main, dev]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ github.ref_name == 'dev' && '/dev/' || '/' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with wasm32 target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Cache Cargo build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            puzzle-wasm

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Build WASM (wasm-pack)
        run: |
          # out-dir is relative to the crate, place output at repo-root ./pkg
          wasm-pack build --target web --release --out-dir ../pkg puzzle-wasm

      - name: Upload wasm pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: pkg

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install web dependencies
        working-directory: web
        run: pnpm install --frozen-lockfile

      - name: Build modern web UI (Vite)
        working-directory: web
        run: pnpm build

      - name: Prepare site for Pages
        run: |
          rm -rf dist
          if [ "$BASE_PATH" = "/dev/" ]; then
            deploy_dir="dist/dev"
          else
            deploy_dir="dist"
          fi
          mkdir -p "$deploy_dir"
          # Copy Vite build
          cp -r web/dist/* "$deploy_dir/"
          # Include WASM pkg and static data
          cp -r pkg "$deploy_dir/"
          cp -r puzzle "$deploy_dir/"
          cp shapes.json "$deploy_dir/"
          cp puzzles.json "$deploy_dir/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
